### ISSUE TITLE
no such file or directory, open './src/assets/presentation.txt

### ISSUE THREAD

**Issue by SploeCyber** [Ayfri/Advanced-Command-Handler#22]
internal/fs/utils.js:298
    throw err;
    ^

Error: ENOENT: no such file or directory, open './src/assets/presentation.txt' at Object.<anonymous> (C:\Users\champ\Desktop\GitHub\Bailey.js\index.js:53:16)
    at Module._compile (internal/modules/cjs/loader.js:1236:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1257:10)
    at Module.load (internal/modules/cjs/loader.js:1085:32)
    at Function.Module._load (internal/modules/cjs/loader.js:950:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: './src/assets/presentation.txt'
}

**Comment by Ayfri** [comment]
This will be in the 1.0.3 that will be released today.
