### ISSUE TITLE
There error is logger file

### ISSUE THREAD

**Issue by Priyanshu348** [Ayfri/Advanced-Command-Handler#7]
/app/utils/Logger.js:8
	static logComments = true;
	                   ^
SyntaxError: Unexpected token =
    at new Script (vm.js:80:7)
    at createScript (vm.js:274:10)
    at Object.runInThisContext (vm.js:326:10)
    at Module._compile (internal/modules/cjs/loader.js:664:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)

**Comment by Ayfri** [comment]
Which version of node do you have ?

**Comment by dev-cord** [comment]
Same issue with me I am using node 10 version..

**Comment by Ayfri** [comment]
NodeJS version 12 is required.
